# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_power', models.FloatField()),
                ('sub_price', models.FloatField()),
                ('kWh_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeographicLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsersLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand-Est', 'Grand-Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Ile-de-France', 'Ile-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur")], default='Ile-de-France', max_length=50)),
                ('power', models.FloatField(choices=[(3, 3), (6, 6), (9, 9), (12, 12), (15, 15)], default=3)),
                ('bill', models.FloatField()),
                ('consumption', models.FloatField(default=0)),
                ('load_profile', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
