# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courbe_de_charge', '0005_auto_20170830_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslp',
            name='location',
            field=models.CharField(choices=[('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand-Est', 'Grand-Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Ile-de-France', 'Ile-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur")], default='Ile-de-France', max_length=50),
        ),
    ]
